name: Build Configurations

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Check flake
      run: nix flake check

    - name: Build NixOS configuration
      run: nixos-rebuild build --flake .#bitcrshr-gaming

    - name: Build Home Manager configuration
      run: nix build .#homeConfigurations.generic

  build-darwin:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - uses: DeterminateSystems/determinate-nix-action@v3

    - name: Check flake
      run: nix flake check

    - name: Build Darwin configuration
      run: nix build --flake .#darwinConfigurations.macbook
